language: node_js

node_js:
  - "4"
  - "6"

branches:
  except:
    - /^v\d+\./

script:
  - "npm run travis"

before_script:
  - "mysql -e 'create database sequelize_test;'"
  - "psql -c 'create database sequelize_test;' -U postgres"
  - "export SEQ_MYSQL_USER=root"
  - "export SEQ_PG_USER=postgres"
  - "export SEQ_PG_PW=postgres"
  - 'if [ "$SEQ_VERSION" ]; then npm install sequelize@^$SEQ_VERSION.0.0; fi'

env:
  global:
    - CXX=g++-4.8
  matrix:
    - DB=mysql DIALECT=mysql
    - DB=mysql DIALECT=postgres
    - DB=mysql DIALECT=postgres-native
    - DB=mysql DIALECT=sqlite
    - DB=mysql DIALECT=mysql SEQ_VERSION=3
    - DB=mysql DIALECT=postgres SEQ_VERSION=3
    - DB=mysql DIALECT=postgres-native SEQ_VERSION=3
    - DB=mysql DIALECT=sqlite SEQ_VERSION=3
    - DB=mysql DIALECT=mysql SEQ_VERSION=2
    - DB=mysql DIALECT=postgres SEQ_VERSION=2
    - DB=mysql DIALECT=postgres-native SEQ_VERSION=2
    - DB=mysql DIALECT=sqlite SEQ_VERSION=2

matrix:
  fast_finish: true
  include:
    - node_js: "4"
      env: DB=mysql DIALECT=mysql COVERAGE=true
  allow_failures:
    - env: DB=mysql DIALECT=mysql COVERAGE=true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  postgresql: "9.3"

sudo: false
